type Calendar {
  id: ID!
  name: String!
  description: String
  color: String
  events(max: Int = 100, start: String = "today"): [Event!]
  access: String
}

type Event {
  id: ID!
  name: String
  description: String
  start: String
  end: String
}

type Meetup {
  start: String
  location: String
  mentor: Mentor
  mentee: Person
}

type Slot {
  id: ID!
  start: String!
  end: String
}
