type Validity {
  field: String
  valid: Boolean!
  reason: String
}

type Google {
  connected: Boolean
  email: String
  canDisconnect: Boolean
}

type Redirect {
  from: String!
  to: String!
  expires: Int
}

scalar Upload

type Image {
  base: String
  sizes: [ImageSize]!
  types: [ImageType]!
}

enum ImageType {
  PNG
  JPEG
  WEBP
}

type ImageSize {
  width: Int
  height: Int
  key: String!
}
