type Validity {
  field: String
  valid: Boolean!
  reason: String
}

type Google {
  connected: Boolean
  email: String
  canDisconnect: Boolean
}

enum GoogleAuthScope {
  SIGN_IN
  SIGN_UP
  CALENDAR
}

type Redirect {
  from: String!
  to: String!
  expires: Int
}

scalar Upload

type Image {
  base: String
  versions: [ImgVersion!]!
}

enum ImageType {
  png
  jpeg
  webp
}

type ImgVersion {
  width: Int
  height: Int
  type: ImageType
  key: String!
}
