type Space {
  id: ID!
  name: String!
  handle: String!
  description: String
  sidebar: String
  mentors(includeOwners: Boolean = true): [Person!]
  members: [Person!]
  owners: [Person!]
  isMember: Boolean
  inviteLinks: SpaceInviteLinks
}

type SpaceInviteLinks {
  founder: ID
  mentor: ID
  owner: ID
}

enum SpaceInviteRole {
  FOUNDER
  MENTOR
  OWNER
}
