directive @private on FIELD_DEFINITION

type User {
  name: String!
  keycode: String!
  role: String
  company: String
  location: String
  website: String
  email: String! @private
}

type Query {
  me: User
  mentors: [User!]!
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  signIn(input: LoginInput): User
  signOut: ID
}

schema {
  query: Query
  mutation: Mutation
}
