directive @private on FIELD_DEFINITION

interface Person {
  name: String!
  email: String
}

type User implements Person {
  name: String!
  email: String @private
}

type Mentor implements Person {
  name: String!
  email: String @private
  keycode: String!
  role: String
  company: String
  location: String
  website: String
}

type Query {
  me: Person
  mentors: [Mentor!]!
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  signIn(input: LoginInput): Person
  signOut: ID
}

schema {
  query: Query
  mutation: Mutation
}
