directive @private on FIELD_DEFINITION

type ProfilePicture {
  size: Int
  type: String
  url: String
}

interface Person {
  name: String!
  email: String
  profilePictures: [ProfilePicture]
}

type User implements Person {
  name: String!
  email: String @private
  profilePictures: [ProfilePicture]
}

type Mentor implements Person {
  name: String!
  email: String @private
  keycode: String!
  role: String
  company: String
  location: String
  website: String
  bio: String
  profilePictures: [ProfilePicture]
}

type Query {
  me: Person
  mentors: [Mentor!]!
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  signIn(input: LoginInput): Person
  signOut: ID
}

schema {
  query: Query
  mutation: Mutation
}
