export { default as schema } from './schema.gql'
export { default as queries } from './queries.gql'
export { default as mutations } from './mutations.gql'
export { default as inputs } from './inputs.gql'
export { default as subscriptions } from './subscriptions.gql'

export { default as calendar } from './types/calendar.gql'
export { default as conversations } from './types/conversations.gql'
export { default as invite } from './types/invite.gql'
export { default as meta } from './types/meta.gql'
export { default as other } from './types/other.gql'
export { default as preferences } from './types/preferences.gql'
export { default as search } from './types/search.gql'
export { default as timezone } from './types/timezone.gql'
export { default as user } from './types/user.gql'
