input LoginInput {
  email: String!
  password: String!
}

input ProfileInput {
  name: String
  keycode: String
  location: String
  role: String
  company: String
  website: String
  bio: String
  dribbble: String
  facebook: String
  github: String
  linkedin: String
  twitter: String
  tags: [String!]
}

input NotificationSettingsInput {
  receiveEmails: Boolean
  slotReminder: EmailInterval
}

input SlotInput {
  start: String!
  duration: Int
}

input SlotUpdateInput {
  deleted: [ID!]
  added: [SlotInput!]
}

input MsgExtInput {
  to: ID!
  name: String!
  email: String!
  message: String!
}

input RequestSlotInput {
  slotId: ID!
  name: String!
  email: String!
  message: String!
}

type Mutation {
  signIn(input: LoginInput!): Person
  signOut: Int
  updateProfile(input: ProfileInput!): Mentor
  requestEmailChange: Int
  requestPasswordChange: Int
  deleteAccount(password: String!): Int
  setProfileVisibility(visibility: Visibility!): Mentor
  updateNotificationPreferences(input: NotificationSettingsInput!): Mentor
  updateSlots(slots: SlotUpdateInput!): Mentor
  messageExt(input: MsgExtInput!): Int
  requestSlot(input: RequestSlotInput!): Int
  acceptMeetup(meetupId: ID!): Meetup
  cancelMeetup(meetupId: ID!): Int
}
