type Query {
  me: Person
  mentors: [Mentor!]!
  mentor(handle: String, id: ID): Mentor @deprecated
  user(handle: String, id: ID): Person
  calendarConnectUrl: String
  tag(id: Int, name: String): Tag
  tags(orderBy: TagOrder = alpha): [Tag!]!
  lists: [List!]!
  list(name: String!): List
  isTokenValid(token: String!): Boolean
  search(
    term: String
    withTags: [Int!]
    withTagNames: [String!]
    maxUsers: Int = 5
    maxTags: Int = 3
  ): SearchResult
  signUpInfo(token: ID!): SignUpInfo
  googleSigninUrl(state: String): String
}
