type Query {
  me: Person
  mentors: [Mentor!]!
  user(handle: String, id: ID): Person
  users(handles: [String], ids: [ID]): [Person!]!
  tag(id: Int, name: String): Tag
  tags(orderBy: TagOrder = alpha): [Tag!]!
  lists(includeUnlisted: Boolean = false): [List!]!
  list(name: String!): List
  isTokenValid(token: String!): Boolean
  search(
    term: String
    withTags: [Int!]
    withTagNames: [String!]
    maxUsers: Int = 5
    maxTags: Int = 3
  ): SearchResult
  signUpInfo(token: ID!): SignUpInfo
  googleSigninUrl(redirect: String!, state: String): String
  googleSignupUrl(redirect: String!, state: String): String
  calendarConnectUrl(redirect: String!): String
  checkValidity(
    name: String
    handle: String
    biography: String
    location: String
    headline: String
  ): [Validity!]!
  conversation(conversationId: ID!): Conversation
  channel(channelId: ID!): Channel
  redirects: [Redirect!]!
  userList(
    sortBy: String = "name"
    order: SortOrder = ASC
    limit: Int = 25
    offset: Int = 0
    search: String
    filter: String
  ): UserConnection!
}
