interface Person {
  id: ID!
  handle: String
  name: String!
  email: String
  location: String
  profilePictures: [ProfilePicture]
  social(includeEmpty: Boolean = false): [SocialHandle!]
  notificationPrefs: NotificationPreferences
  biography: String
  tags: [String!]
  website: String
  categories: [String!]
  role: Role
}

type User implements Person {
  id: ID!
  handle: String
  name: String!
  email: String
  location: String
  profilePictures: [ProfilePicture]
  social(includeEmpty: Boolean = false): [SocialHandle!]
  notificationPrefs: UserNotificationPreferences
  biography: String
  tags: [String!]
  website: String
  categories: [String!]
  role: Role
}

type Mentor implements Person {
  id: ID!
  handle: String!
  name: String!
  email: String
  title: String
  company: String
  location: String
  website: String
  biography: String
  profilePictures: [ProfilePicture!]!
  social(includeEmpty: Boolean = false): [SocialHandle!]
  tags: [String!]
  visibility: Visibility
  notificationPrefs: MentorNotificationPreferences
  slots(after: String, before: String, includeBooked: Boolean = false): [Slot!]!
  calendars(ids: [ID!]): [Calendar!]
  calendarConnected: Boolean
  categories: [String!]
  role: Role
}

type Calendar {
  id: ID!
  name: String
  description: String
  color: String
  events(max: Int = 100, start: String = "today"): [Event!]
}

type Event {
  id: ID!
  name: String
  description: String
  start: String
  end: String
}

type Meetup {
  start: String
  location: String
  mentor: Mentor
  mentee: Person
}

enum Visibility {
  LISTED
  UNLISTED
}

type Slot {
  id: ID!
  start: String!
  end: String
}

interface NotificationPreferences {
  receiveEmails: Boolean
}

type UserNotificationPreferences implements NotificationPreferences {
  receiveEmails: Boolean
}

type MentorNotificationPreferences implements NotificationPreferences {
  receiveEmails: Boolean
  slotReminder: EmailInterval
}

enum EmailInterval {
  MONTHLY
  WEEKLY
  OFF
}

type ProfilePicture {
  size: Int
  type: String
  url: String
}

type SocialHandle {
  id: Int!
  name: String
  url: String
  handle: String
}

enum Role {
  USER
  MENTOR
  NOLOGIN
  ADMIN
}

type Tag {
  id: Int!
  name: String!
  users: [User!]
}

enum TagOrder {
  alpha
}

type List {
  id: Int
  name: String!
  users: [Person!]
}

scalar Upload

type SearchResult {
  users: [User!]!
  userResults: Int
  tags: [Tag!]!
}
